In [1]:
import datetime as dt
import pandas as pd
import numpy as np
import plotly.express as px
import yfinance as yf

c:\Users\danie\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

Raw Data Gathering

In [2]:
effr_raw=pd.read_csv("https://markets.newyorkfed.org/api/rates/unsecured/effr/last/61.csv")
effr=effr_raw.copy()
effr['FF']=effr['Rate (%)']
effr['FF CoD']=effr['FF'].diff(periods=-1)*100


effr['FF to mid target']=(effr['FF']-((effr['Target Rate From (%)']+effr['Target Rate To (%)'])/2))*100
effr

,Effective Date,Rate Type,Rate (%),1st Percentile (%),25th Percentile (%),75th Percentile (%),99th Percentile (%),Volume ($Billions),Target Rate From (%),Target Rate To (%),...,Standard Deviation (%),30-Day Average SOFR,90-Day Average SOFR,180-Day Average SOFR,SOFR Index,Revision Indicator (Y/N),Footnote ID,FF,FF CoD,FF to mid target
0,10/10/2024,EFFR,4.83,4.81,4.82,4.84,4.85,98,4.75,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.83,0.0,-4.5
1,10/09/2024,EFFR,4.83,4.81,4.83,4.84,4.85,94,4.75,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.83,0.0,-4.5
2,10/08/2024,EFFR,4.83,4.81,4.83,4.84,4.85,90,4.75,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.83,0.0,-4.5
3,10/07/2024,EFFR,4.83,4.81,4.83,4.84,4.85,86,4.75,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.83,0.0,-4.5
4,10/04/2024,EFFR,4.83,4.81,4.83,4.84,4.85,84,4.75,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.83,0.0,-4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,07/23/2024,EFFR,5.33,5.31,5.32,5.34,5.45,85,5.25,5.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.33,0.0,-4.5
57,07/22/2024,EFFR,5.33,5.31,5.32,5.34,5.45,84,5.25,5.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.33,0.0,-4.5
58,07/19/2024,EFFR,5.33,5.31,5.32,5.34,5.45,79,5.25,5.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.33,0.0,-4.5
59,07/18/2024,EFFR,5.33,5.31,5.32,5.34,5.35,83,5.25,5.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.33,0.0,-4.5
60,07/17/2024,EFFR,5.33,5.31,5.33,5.34,5.45,80,5.25,5.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.33,NaN,-4.5

In [3]:

effr=effr[['Effective Date','FF','FF CoD','FF to mid target']]

effr

   Effective Date    FF  FF CoD  FF to mid target
0      10/10/2024  4.83     0.0              -4.5
1      10/09/2024  4.83     0.0              -4.5
2      10/08/2024  4.83     0.0              -4.5
3      10/07/2024  4.83     0.0              -4.5
4      10/04/2024  4.83     0.0              -4.5
..            ...   ...     ...               ...
56     07/23/2024  5.33     0.0              -4.5
57     07/22/2024  5.33     0.0              -4.5
58     07/19/2024  5.33     0.0              -4.5
59     07/18/2024  5.33     0.0              -4.5
60     07/17/2024  5.33     NaN              -4.5

[61 rows x 4 columns]

In [4]:
sofr_raw=pd.read_csv('https://markets.newyorkfed.org/api/rates/secured/sofr/last/91.csv')
sofr=sofr_raw.copy()
sofr['SOFR']=sofr['Rate (%)']
sofr['SOFR CoD']=sofr['SOFR'].diff(periods=-1)*100
sofr=sofr[['Effective Date','SOFR','SOFR CoD']]

effr_sofr=pd.merge(effr,sofr,how='right')
effr_sofr=effr_sofr.rename(columns={'Effective Date':'Value Date'})
effr_sofr['Value Date']=pd.to_datetime(effr_sofr['Value Date'])
effr_sofr['Value Date']=effr_sofr['Value Date'].dt.strftime("%a %d%b%y")

effr_sofr_backfilled=effr_sofr[:90].copy()
effr_sofr_backfilled.fillna(method='bfill',inplace=True)
effr_sofr['FF - SOFR Spread']=(effr_sofr['FF']-effr_sofr['SOFR'])*100
effr_sofr=effr_sofr.fillna('')
effr_sofr

     Value Date    FF FF CoD FF to mid target  SOFR SOFR CoD FF - SOFR Spread
0   Thu 10Oct24  4.83    0.0             -4.5  4.82     -1.0              1.0
1   Wed 09Oct24  4.83    0.0             -4.5  4.83     -1.0              0.0
2   Tue 08Oct24  4.83    0.0             -4.5  4.84      1.0             -1.0
3   Mon 07Oct24  4.83    0.0             -4.5  4.83      0.0              0.0
4   Fri 04Oct24  4.83    0.0             -4.5  4.83     -2.0              0.0
..          ...   ...    ...              ...   ...      ...              ...
86  Fri 07Jun24                                5.33      0.0
87  Thu 06Jun24                                5.33      0.0
88  Wed 05Jun24                                5.33      0.0
89  Tue 04Jun24                                5.33     -2.0
90  Mon 03Jun24                                5.35

[91 rows x 7 columns]

In [5]:
# Get SOFR Futures (3 month) data from Yahoo Finance
ticker = 'SR3=F'

# Download the latest market data for the 3-month SOFR future
sofr_data = yf.Ticker(ticker)

In [24]:
used_ff_rate = effr_sofr['FF'][0]
used_ff_rate

4.83

In [23]:

# Get the current price (last closing price)
current_price = round(sofr_data.history(period="1d")['Close'].iloc[-1],3)

# Display the current price of the 3-month SOFR future
print(f"The latest 3-month SOFR future price is: {current_price}")
priced_in=round(100-current_price-used_ff_rate,3)
print(f"Amount of basis point cuts/hikes priced in is {priced_in}")
print(f"{priced_in//-.25} cuts are priced in with a {abs(priced_in%-.25/.25*100)}% chance of another cut")

The latest 3-month SOFR future price is: 95.66
Amount of basis point cuts/hikes priced in is -0.41
1.0 cuts are priced in with a 63.99999999999999% chance of another cut